#include <stdio.h>
#include <string.h>
#include "amiguard_ae.h"
#include "arexx_dispatch.h"
static int expect(const char *c,long rc,const char *s){AmiGuardAERexxResult r;amiguard_ae_arexx_dispatch(c,&r);if(r.rc!=rc||strcmp(r.result,s)!=0)return 0;printf("SMOKE PASS %s => %s\n",c,r.result);return 1;}
static int expect_prefix(const char*c,long rc,const char*p){AmiGuardAERexxResult r;unsigned long n=(unsigned long)strlen(p);amiguard_ae_arexx_dispatch(c,&r);if(r.rc!=rc||strncmp(r.result,p,n)!=0)return 0;printf("SMOKE PASS %s => %s\n",c,r.result);return 1;}
static int write_file(const char*p,const unsigned char*d,unsigned long n){FILE*f=fopen(p,"wb");if(f==0)return 0;if(fwrite(d,1U,(size_t)n,f)!=(size_t)n){fclose(f);return 0;}fclose(f);return 1;}
int main(void){static const unsigned char crc[]="123456789";static const unsigned char hunk[]={0,0,3,0xF3};int ok=1;if(!write_file("RAM:amiguard-ae-crc.bin",crc,9UL)||!write_file("RAM:amiguard-ae-hunk.bin",hunk,4UL))return AMIGUARD_AE_RC_FAIL;
ok=expect("PING",0,"PONG")&&ok;ok=expect("STATUS",0,"READY M3.4 scanner=connected")&&ok;ok=expect("SIGNATURE.STATUS",0,"READY COUNT=4 UPDATE=UNAVAILABLE")&&ok;ok=expect("SIGNATURE.STATUS now",10,"ERROR SIGNATURE.STATUS takes no arguments")&&ok;ok=expect("SIGNATURE.COUNT",0,"4")&&ok;ok=expect("SIGNATURE.INFO 0",0,"INDEX=0 TYPE=BOOTBLOCK OFFSET=64 LENGTH=8 TEST_ONLY=0 NAME=AmiGuard.Test.Marker")&&ok;ok=expect("SIGNATURE.UPDATE",10,"ERROR signature updater unavailable")&&ok;ok=expect_prefix("SCAN RAM:amiguard-ae-crc.bin",0,"CLEAN ")&&ok;ok=expect("RESULT.STATUS",0,"CLEAN")&&ok;ok=expect("CHECKSUM RAM:amiguard-ae-crc.bin",0,"CRC32 CBF43926")&&ok;ok=expect("IDENTIFY RAM:amiguard-ae-hunk.bin",0,"AMIGA-HUNK HUNK_HEADER")&&ok;ok=expect("RESULT.CLEAR",0,"OK")&&ok;remove("RAM:amiguard-ae-crc.bin");remove("RAM:amiguard-ae-hunk.bin");if(!ok)return AMIGUARD_AE_RC_FAIL;puts("M3.4 AROS signature status smoke: PASS");return 0;}
