name: host-check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Host qualification
        run: |
          make clean
          make check
          make
          ./AmiGuardAE
